### ISSUE TITLE
Something to say.

### ISSUE THREAD

**Issue by Ir1d** [Dev-XYS/Algorithms#3]
>* https://github.com/24OI/Standard_Code_Library/issues/4 这里有一些知识点整理

>* 推荐 SATA 协议 https://github.com/zTrix/sata-license

>* 第三件事一时间想不起来了…… 

**相信你们能够创造更多的伟大！**

**Comment by Dev-XYS** [comment]
谢谢学长的鼓励！我们会努力的。

**Comment by Ir1d** [comment]
哎 第三件事是之前把Claris大佬的板子放到群里了 那个ACMICPC Templates
