### ISSUE TITLE
Splay与STL的set对拍不通过

### ISSUE THREAD

**Issue by Dev-XYS** [Dev-XYS/Algorithms#4]
&emsp;&emsp;目前版本的Splay在第一次查找已存在的元素时返回-1。

**Comment by Dev-XYS** [comment]
&emsp;&emsp;错误已修正，并简化代码。

**Comment by Ir1d** [comment]
现在写的是汝佳老师版本的splay？bzoj维修数列用它写好写吗

**Comment by Dev-XYS** [comment]
&emsp;&emsp;经过两个月之久的调试，历经多次重写并尝试使用多种方式的Splay进行维护，我终于AC了维修数列！这是我的代码：[BZOJ - 1500](https://github.com/Dev-XYS/OI-Problems/blob/master/bzoj/1500.cpp)。

**Comment by Ir1d** [comment]
好评如潮 恭喜恭喜
