### ISSUE TITLE
你好，我在二叉搜索树中有个问题

### ISSUE THREAD

**Issue by linabellbiu** [Dev-XYS/Algorithms#6]
为什么最后返回的是satellite 这个值，能把key 和 satellite 注释一下吗，谢谢

**Comment by Ir1d** [comment]
key是下标 satellite是值(大概

**Comment by linabellbiu** [comment]
如果说satellite是值 的话  那么 lch 和rch 是什么，不好意思 ，我是小白。

**Comment by Dev-XYS** [comment]
&emsp;&emsp;satellite是“卫星数据”，也就是一个关键字对应的需要存储的数据。实际上，本代码实现了一个从key到satellite的映射，即map。

**Comment by linabellbiu** [comment]
非常感谢你的解答
